## Configuration Options for Pattern Lab

# pattern lab version
v: "2.6.0"

# what to do when included config var conflicts, q for question, a for always override, n for never override
overrideConfig: "q"

# file extensions to ignore when building or watching the source dir, separate with a comma
ie:
  - "DS_Store"
  - "less"
  - "scss"

# directories and files to ignore when building or watching the source dir, separate with a comma
id:
  - "scss"
  - ".svn"
  - ".sass-cache"

# whether the public directory should be cleaned when generating your site
cleanPublic: "true"

# the order of pattern states, css class names
patternStates:
  - "inprogress"
  - "inreview"
  - "complete"

# the pattern types that shouldn't be included in the style guide, useful if you nest pages/templates
styleGuideExcludes: ""

# should the cache buster be on, set to false to set the cacheBuster value to 0
cacheBusterOn: "true"

# project directories
exportDir: "export"
publicDir: "<%= buildPath %>/pattern-library"
sourceDir: "<%= patternPath %>"

# defaultPattern to show on load
defaultPattern: "all"

# show pattern info by default on the "view all" views
defaultShowPatternInfo: false

# ish
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
    - hay

# twig engine settings
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
lineageMatch: '{%([ ]+)?(?:include|extends|embed)( |\()[&quot;\&#039;]([\/.@A-Za-z0-9-_]+)[&quot;\&#039;]([\s\S+]*?)%}'
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: html
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
plugins:
    faker:
        enabled: true
        locale: nl_NL
